export interface ReactServerConfig {
  scheduleWork: unknown
  scheduleMicrotask: unknown
  beginWriting: unknown
  writeChunk: unknown
  writeChunkAndReturn: unknown
  completeWriting: unknown
  flushBuffered: unknown
  close: unknown
  closeWithError: unknown
  stringToChunk: unknown
  stringToPrecomputedChunk: unknown
  typedArrayToBinaryChunk: unknown
  byteLengthOfChunk: unknown
  byteLengthOfBinaryChunk: unknown
  createFastHash: unknown
  bindToConsole: unknown
  resetResumableState: unknown
  completeResumableState: unknown
  getChildFormatContext: unknown
  makeId: unknown
  pushTextInstance: unknown
  pushStartInstance: unknown
  pushEndInstance: unknown
  pushStartCompletedSuspenseBoundary: unknown
  pushEndCompletedSuspenseBoundary: unknown
  pushSegmentFinale: unknown
  pushFormStateMarkerIsMatching: unknown
  pushFormStateMarkerIsNotMatching: unknown
  writeCompletedRoot: unknown
  writePlaceholder: unknown
  writeStartCompletedSuspenseBoundary: unknown
  writeStartPendingSuspenseBoundary: unknown
  writeStartClientRenderedSuspenseBoundary: unknown
  writeEndCompletedSuspenseBoundary: unknown
  writeEndPendingSuspenseBoundary: unknown
  writeEndClientRenderedSuspenseBoundary: unknown
  writeStartSegment: unknown
  writeEndSegment: unknown
  writeCompletedSegmentInstruction: unknown
  writeCompletedBoundaryInstruction: unknown
  writeClientRenderBoundaryInstruction: unknown
  NotPendingTransition: unknown
  writePreamble: unknown
  writeHoistables: unknown
  writeHoistablesForBoundary: unknown
  writePostamble: unknown
  hoistHoistables: unknown
  createHoistableState: unknown
  emitEarlyPreloads: unknown
}
