#!/usr/bin/env -S bun run --watch --conditions=react-server
// yarn workspace reframe-server-demo-rsc run demo

import { ReFrameServer } from "@double-observer/reframe/server"
import Bun from "bun"
import React, { type ReactElement, type ReactNode } from "react"

console.info(React.version) // allows React to not be removed when organizing dependencies
;(global as any).__DEV__ = true

// function Demo() {
//   return (
//     <>
//       <View className="overflow-hidden rounded bg-white/20">
//         <StreamingFragment>{renderChunkedTimestamps}</StreamingFragment>
//         <Image />
//         <ProfileImageView />

//         <View>
//           <Text>View</Text>
//         </View>

//         <LinearGradient colors={["#f00", "#00f"]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
//           <Text>LinearGradient</Text>
//         </LinearGradient>

//         <ScrollView horizontal style={{ maxHeight: 123 }}>
//           <Text>ScrollView</Text>
//         </ScrollView>

//         <Text>Text</Text>

//         <Switch>
//           <Text>Switch</Text>
//         </Switch>

//         <Pressable>
//           <Text>Pressable</Text>
//         </Pressable>

//         <TextInput>
//           <Text>TextInput</Text>
//         </TextInput>

//         <Button
//           title="Button"
//           onPress={{ isClientAction: true, action: "Alert2", title: "Button" }}
//         />

//         <AnimatedButton
//           onPress={{ isClientAction: true, action: "Alert2", title: "AnimatedButton" }}
//         >
//           <Text>AnimatedButton</Text>
//         </AnimatedButton>

//         <TouchableHighlight
//           onPress={{ isClientAction: true, action: "Alert2", title: "TouchableHighlight" }}
//           activeOpacity={0.5}
//           underlayColor="#FF0000"
//         >
//           <Text>TouchableHighlight</Text>
//         </TouchableHighlight>

//         <TouchableOpacity
//           onPress={{
//             isClientAction: true,
//             actions: [
//               { action: "Haptics", haptic: "hapticSuccess" },
//               { action: "Alert2", title: "TouchableWithoutFeedback" },
//             ],
//           }}
//         >
//           <Text>TouchableOpacity</Text>
//         </TouchableOpacity>

//         <TouchableWithoutFeedback
//           onPress={{ isClientAction: true, action: "Alert2", title: "TouchableWithoutFeedback" }}
//         >
//           <Text>TouchableWithoutFeedback</Text>
//         </TouchableWithoutFeedback>

//         <BlurView
//           tint="dark"
//           intensity={12.5}
//           className="pointer-events-none absolute bottom-3 left-1/4 right-3 top-3 z-10"
//         >
//           <Text>BlurView</Text>
//         </BlurView>
//       </View>
//     </>
//   )
// }

function ErrorView(): ReactNode {
  throw Object.assign(new Error("This is an error"), { name: "ErrorViewError" })
}

async function AsyncErrorView(): Promise<ReactElement> {
  await new Promise((wake) => setTimeout(wake, 123))
  throw Object.assign(new Error("This is an async error"), { name: "AsyncErrorViewError" })
}

async function renderToRSC(ui: AsyncIterable<string>, microSpiritViewFile: ReturnType<typeof Bun.file>) {
  Bun.write(microSpiritViewFile, (await Array.fromAsync(ui)).join(""))
  console.info(`Wrote ${microSpiritViewFile.name}`)
}

async function renderToDevView(ui: AsyncIterable<string>, microSpiritViewFile: ReturnType<typeof Bun.file>) {
  const chunksToWrite: string[] = []
  const chunks = generatePrerenderedRSC(ui)
  for await (const chunk of chunks) {
    chunksToWrite.push(chunk)
  }
  Bun.write(microSpiritViewFile, chunksToWrite.join(""))
  console.info(`Wrote ${microSpiritViewFile.name}`)
}

function prettifyChunk(chunk: string) {
  return JSON.stringify(chunk)
}

async function* generatePrerenderedRSC(ui: AsyncIterable<string>) {
  // yield `// prettier-ignore\n`
  yield `// GENERATED CODE - DO NOT MODIFY DIRECTLY`
  yield `\n`
  yield `// This code was generated by ${__filename.replace(/^.*[/]packages/, "packages")}`
  yield `\n`
  yield `export default { async *[Symbol.asyncIterator]() {`
  yield `\n`

  let index = -1
  let timeStart = Date.now()
  yield "  /* "
  for await (const chunk of ui) {
    yield " */\n"
    ++index
    if (index > 0) {
      const elapsedTime = Math.max(0, Date.now() - timeStart)
      yield /* js */ `  await new Promise(wake => setTimeout(wake, ${elapsedTime}))`
      yield `\n`
    }
    yield /* js */ `  yield ${prettifyChunk(chunk)}`
    yield `\n`
    timeStart = Date.now()
    yield "  /* "
  }
  yield "// */\n"
  yield "} } satisfies AsyncIterable<string>"
  yield `\n`
}

function Demo() {
  return <div>hwllo</div>
}

// function View() {
//   return
// }

const View = "div"

// const url = require("url")
// new URL(".", url.pathToFileURL(__filename)).href
const clientBundle = {}
console.log(clientBundle)

async function main() {
  debugger
  // await renderToDevView(
  //   ReFrameServer.renderToAsyncIterable(<Demo key={Date.now()} />, clientBundle),
  //   Bun.file(`${__filename}.Demo.ts`),
  // )
  // await renderToRSC(
  //   ReFrameServer.renderToAsyncIterable(<Demo key={Date.now()} />, clientBundle),
  //   Bun.file(`${__filename}.Demo.rsc`),
  // )

  for await (const chunk of ReFrameServer.renderToAsyncIterable(<Demo key={Date.now()} />, clientBundle)) {
    console.log(chunk)
  }

  // await renderToDevView(
  //   ReFrameServer.renderToAsyncIterable(
  //     <View>
  //       <ErrorView />
  //       <Suspense>
  //         <AsyncErrorView />
  //       </Suspense>
  //     </View>,
  //     clientBundle,
  //   ),
  //   Bun.file(`${__filename}.ErrorView.ts`),
  // )
  // await renderToRSC(
  //   ReFrameServer.renderToAsyncIterable(
  //     <View>
  //       <ErrorView />
  //       <Suspense>
  //         <AsyncErrorView />
  //       </Suspense>
  //     </View>,
  //     clientBundle,
  //   ),
  //   Bun.file(`${__filename}.ErrorView.rsc`),
  // )
}

debugger
// main()
global.main = main

// const renderChunkedTimestamps = {
//   async *[Symbol.asyncIterator]() {
//     yield { replace: <Text>loading...</Text> }

//     const response = await fetch("http://localhost:8000")
//     yield { replace: <Text>response: {response.status}</Text> }

//     await new Promise((resolve) => setTimeout(resolve, 333))

//     const { body } = response

//     if (!body) {
//       yield <Text>ERROR: no body</Text>
//       return
//     }
//     for await (const chunk of body) {
//       const random = Math.random()
//       yield {
//         replace: (
//           <Text
//             style={{
//               // random background color so it's easier to see that something changed
//               backgroundColor: `hsl(${random * 360}, 50%, 50%)`,
//               color: "white",
//               fontVariant: ["tabular-nums"],
//             }}
//           >
//             {new TextDecoder().decode(chunk).trim()}
//           </Text>
//         ),
//       }
//     }

//     yield <Text>{"\n\n"}Done</Text>
//   },
// }
